Updates README and adds docs
InfiniteRasa/Rasa.NET pull request #41
Opened 2019-02-06 18:46 UTC by infiniterasadev

- Update the README to be a little more welcoming.
- Create a /docs and /images folder to contain documentation and screenshots
- Added setup.md which is a first run at an updated setup guide.
- Added screenshot.jpg which is a picture of the servers running for some flare on the README

2019-02-06 18:56 UTC, Blumster requested changes

2019-02-06 18:56 UTC, Blumster commented on README.md
> +A C# implementation of a game and authentication server for Tabula Rasa running on .NET Core.
Don't include copyrighted names for legal reasons.

2019-02-06 18:56 UTC, Blumster commented on docs/setup.md
> +This guide will help you install and setup the required tools to run Tabula Rasa using Rasa.NET. There are a few steps:
Don't include copyrighted names for legal reasons.

2019-02-06 18:56 UTC, Blumster commented on docs/setup.md
> +3. Patch Tabula Rasa using a custom patcher
Don't include copyrighted names for legal reasons.

2019-02-06 18:56 UTC, Blumster commented on docs/setup.md
> +2. Download and install Tabula Rasa
Don't include copyrighted names for legal reasons.

2019-02-06 18:56 UTC, Blumster commented on docs/setup.md
> +6. Launch Tabula Rasa
Don't include copyrighted names for legal reasons.

2019-02-06 18:56 UTC, Blumster commented on docs/setup.md
> +## Download and install Tabula Rasa
Don't include copyrighted names for legal reasons. (In the whole section too.)

2019-02-06 18:56 UTC, Blumster commented on docs/setup.md
> +## Patch Tabula Rasa using the custom patcher
Don't include copyrighted names for legal reasons. (In the whole section too.)

2019-02-06 18:56 UTC, Blumster commented on docs/setup.md
> +- Select the `rasaauth` schema and doubl-click it to make it active
You can create account to your own liking in the authentication server command prompt with your username, email and password. Would be better if you have documented the process how to do that.

2019-02-06 18:56 UTC, Blumster commented on docs/setup.md
> +## Launch Tabula Rasa
Don't include copyrighted names for legal reasons.

2019-02-06 19:02 UTC, infiniterasadev commented
Fixed!

2019-02-06 19:43 UTC, Dahrkael commented
Regarding the screenshot, I'd enforce the same thing as @Blumster requested. Blur that part and blame whoever put that there.

2019-02-06 20:11 UTC, Blumster requested changes

2019-02-06 20:11 UTC, Blumster commented on docs/setup.md
> +- Run the command `create test@test.com test test` in the Authentication server terminal to create a new user
Specify the usage and that they can create their own account, anything they want, and give a basic usage, like you did now.

2019-02-06 22:44 UTC, Blumster requested changes
Please modify the Download and install the game, remove any reference to an actual game. (Paths, exe names, ...), and refer to the forum about downloading the game. Only include the start of the game with specific parameters.

2019-02-07 11:49 UTC, Blumster approved these changes

2019-02-07 11:51 UTC, merged